FanfikSite/Models/UserViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanfikSite.Models;

namespace FanfikSite.Models.UserViewModels
{
    public class UserViewModel
    {
        public ApplicationUser User { get; set; }
        public bool IsAdmin { get; set; }

    }
}

FanfikSite/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using FanfikSite.Models.PostViewModels;
using FanfikSite.Models;
using Dropbox.Api.Files;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using WkWrap.Core;
using FanfikSite.Services;

namespace FanfikSite.Controllers
{
    public class PostController : BaseController
    {
        private readonly IViewRenderService _viewRenderService;

        public PostController(IServiceProvider provider, IViewRenderService viewRenderService) : base(provider)
        {
            _viewRenderService = viewRenderService;
        }

        [HttpGet]
        [Authorize]
        public IActionResult CreatePost(string id)
        {
            var model = new PostViewModel()
            {
                Genres = ApplicationDbContext.Genre.ToList(),
                CreatorId = id ?? CurrentUser.Id
            };
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreatePost(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                Fanfik fanfik = new Fanfik
                {
                    Id = Guid.NewGuid(),
                    Title = model.Title,
                    Shortcut = model.Shortcut,
                    Created = DateTime.Now,
                    Updated = DateTime.Now,
                    Rating = 0,
                    Creator = await ApplicationDbContext.Users.FirstOrDefaultAsync(c => c.Id == model.CreatorId),
                    Genre = await ApplicationDbContext.Genre.FirstOrDefaultAsync(g => g.Name == model.Genre)
                };

                if (model.Photo != null)
                {
                    var link = await SaveImage(model.Photo, fanfik.Id.ToString());
                    fanfik.Image = link;
                }

                AddTags(fanfik, model.Tags);
                ApplicationDbContext.Fanfik.Add(fanfik);
                await ApplicationDbContext.SaveChangesAsync();
                return Redirect("/Post/Get/" + fanfik.Id);
            }

            return View(model);
        }

        [HttpGet]
        [ActionName("Get")]
        public IActionResult GetPost(Guid id)
        {
            if (id != null)
            {
                var fanfik = ApplicationDbContext.Fanfik
                    .Include(f => f.Creator)
                    .FirstOrDefault(f => f.Id == id);
                if (fanfik != null)
                {
                    var model = new GetPostViewModel()
                    {
                        Fanfik = fanfik,
                        Comments = ApplicationDbContext.Comment.Where(c => c.Fanfik == fanfik).ToList(),
                        Tags = ApplicationDbContext.FanfikTag.Where(ft => ft.Fanfik == fanfik).Select(ft => ft.Tag).ToList(),
                        Chapters = ApplicationDbContext.Chapter.Where(c => c.Fanfik == fanfik).ToList(),
                        CurrentUser = CurrentUser
                    };

                    return View(model);
                }
            }
            return NotFound();
        }

        [HttpGet]
        [Authorize]
        public IActionResult AddChapter(Guid fanfikId)
        {
            if (fanfikId == null)
                return NotFound();

            var model = new AddChapterViewModel()
            {
                FanfikFk = ApplicationDbContext.Fanfik.FirstOrDefault(f => f.Id == fanfikId).Id
            };

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddChapter(AddChapterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var chaptersCount = ApplicationDbContext.Chapter.Where(c => c.FanfikFk == model.FanfikFk).ToList().Count;
                var fanfik = ApplicationDbContext.Fanfik.FirstOrDefault(f => f.Id == model.FanfikFk);
                
                var chapter = new Chapter()
                {
                    Id = Guid.NewGuid(),
                    Fanfik = fanfik,
                    Name = model.Name,
                    Context = model.Context,
                    SerialNumber = chaptersCount + 1
                };

                if (model.OptionIlistrutation != null)
                {
                    var link = await SaveImage(model.OptionIlistrutation, Guid.NewGuid().ToString());
                    chapter.OptionIlistrutation = link;
                }

                fanfik.Updated = DateTime.Now;

                ApplicationDbContext.Fanfik.Update(fanfik);
                ApplicationDbContext.Chapter.Add(chapter);
                ApplicationDbContext.SaveChanges();
                return Redirect("/Post/Get/" + chapter.FanfikFk);
            }
            return View(model);
        }

        [HttpGet]
        [ActionName("Chapter")]
        public async Task<IActionResult> GetChapter(Guid id)
        {
            if(id != null)
            {
                var chapter = await ApplicationDbContext.Chapter
                    .Include(c => c.Ratings)
                    .FirstOrDefaultAsync(c => c.Id == id);

                var fanfik = await ApplicationDbContext.Fanfik
                    .Include(f => f.Chapters)
                    .FirstOrDefaultAsync(f => f.Id == chapter.FanfikFk);
                fanfik.Chapters = fanfik.Chapters.OrderBy(c => c.SerialNumber).ToList();

                var commets = ApplicationDbContext.Comment
                    .Include(c => c.Likes)
                    .Include(c => c.Creator)
                    .Where(c => c.Fanfik == fanfik)
                    .OrderBy(c => c.Created);

                var rating = User.Identity
                    .IsAuthenticated ?
                    ApplicationDbContext.Rating.FirstOrDefault(r => r.User == CurrentUser && r.Chapter == chapter) : null;

                List<Guid> likeComments = new List<Guid>();

                if(CurrentUser != null)
                {
                    likeComments = ApplicationDbContext.Like
                    .Include(l => l.Comment)
                    .Include(l => l.Creator)
                    .Where(l => l.Creator == CurrentUser)
                    .Select(l => l.Comment)
                    .Select(c => c.Id)
                    .ToList();
                }

                var model = new GetChapterViewModel()
                {
                    Chapter = chapter,
                    Fanfik = fanfik,
                    Comments = commets.ToList(),
                    Rating = rating,
                    LikeComments = likeComments
                };
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        [Authorize]
        public JsonResult AddLike(Guid commentId)
        {
            if (commentId != null)
            {
                var comment = ApplicationDbContext.Comment.FirstOrDefault(c => c.Id == commentId);
                if (commentId != null)
                {
                    var like = new Like()
                    {
                        Id = Guid.NewGuid(),
                        Creator = CurrentUser,
                        Comment = comment
                    };

                    ApplicationDbContext.Like.Add(like);
                    ApplicationDbContext.SaveChanges();
          
                    return Json(ApplicationDbContext.Like.Where(l => l.Comment == comment).Count());
                }
            }
            return Json(-1);
        }

        [HttpPost]
        [Authorize]
        public JsonResult DeleteChapter(Guid id)
        {
            if (id == null)
                return Json(-1);

            var chapter = ApplicationDbContext.Chapter.FirstOrDefault(c => c.Id == id);
            ApplicationDbContext.Chapter.Remove(chapter);
            ApplicationDbContext.SaveChanges();
            return Json(1);
        }

        private void DeleteFanfik(Guid id)
        {
            var fanfik = ApplicationDbContext.Fanfik
                .Include(f => f.Comments)
                .ThenInclude(c => c.Likes)
                .FirstOrDefault(c => c.Id == id);

            var fanfikTag = ApplicationDbContext.FanfikTag
                .Where(ft => ft.Fanfik == fanfik);

            var chapters = ApplicationDbContext.Chapter
                .Include(c => c.Ratings)
                .Where(c => c.Fanfik == fanfik);

            foreach (var chapter in chapters)
                ApplicationDbContext.Rating.RemoveRange(chapter.Ratings);

            foreach (var comment in fanfik.Comments)
                ApplicationDbContext.Like.RemoveRange(comment.Likes);

            ApplicationDbContext.Comment.RemoveRange(fanfik.Comments);
            ApplicationDbContext.Chapter.RemoveRange(chapters);
            ApplicationDbContext.FanfikTag.RemoveRange(fanfikTag);
            ApplicationDbContext.Fanfik.Remove(fanfik);
            ApplicationDbContext.SaveChanges();
        }

        [Authorize]
        public JsonResult GetComments(int count, Guid fanfikId)
        {
            var comments = ApplicationDbContext.Comment
                .Include(c => c.Creator)
                .Where(c => c.FanfikFk == fanfikId)
                .OrderBy(c => c.Created)
                .ToList();
                 
            if(comments.Count > count)
                return Json(comments.GetRange(count, comments.Count - count).ToList());

            return Json(-1);
        }

        [HttpPost]
        [Authorize]
        public JsonResult DeletePostJson(Guid id)
        {
            if (id == null)
                return Json(-1);

            DeleteFanfik(id);

            return Json(0);
        }
        
        [Authorize]
        public IActionResult DeletePost(Guid id)
        {

FanfikSite/Controllers/UserController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using FanfikSite.Models.UserViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using FanfikSite.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FanfikSite.Controllers
{
    public class UserController : BaseController
    {
        public UserController(IServiceProvider provider) : base(provider)
        {
        }

        [HttpPost]
        public async Task<JsonResult> DeleteUser(string id)
        {
            if (id != null || !IsAdmin)
            {
                var user = ApplicationDbContext.Users.FirstOrDefault(u => u.Id == id);
                if (user != null)
                {
                    user.IsDeleted = true;
                    ApplicationDbContext.Users.Update(user);
                    ApplicationDbContext.SaveChanges();
                    await _userManager.UpdateSecurityStampAsync(user);
                    await _userManager.SetLockoutEndDateAsync(user, DateTimeOffset.MaxValue);

                    return Json(1);
                }
            }
            return Json(0);
        }

        [HttpPost]
        public async Task<JsonResult> BlockUser(string id)
        {
            if (id != null || !IsAdmin)
            {
                var user = ApplicationDbContext.Users.FirstOrDefault(u => u.Id == id);
                await _userManager.SetLockoutEndDateAsync(user, (DateTimeOffset)DateTime.Now.AddDays(7));
                await _userManager.UpdateSecurityStampAsync(user);
                return Json(1);
            }
            return Json(0);
        }

        [HttpPost]
        public JsonResult UnblockUser(string id)
        {
            if (id != null || !IsAdmin)
            {
                var user = ApplicationDbContext.Users.FirstOrDefault(u => u.Id == id);
                _userManager.SetLockoutEndDateAsync(user, DateTimeOffset.UtcNow).GetAwaiter().GetResult();
                return Json(1);
            }
            return Json(0);
        }

        [HttpPost]
        public async Task<JsonResult> AddAdmin(string id)
        {
            if (id != null || !IsAdmin)
            {
                var user = ApplicationDbContext.Users.FirstOrDefault(u => u.Id == id);
                await _userManager.AddToRoleAsync(user, "Admin");
                return Json(1);
            }
            return Json(0);
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (!IsAdmin)
            {
                var users = ApplicationDbContext.Users
                .Where(u => u.IsDeleted != true)
                .Include(u => u.Fanfiks)
                .ToList();

                var model = new UsersViewModel();

                foreach (var user in users)
                {
                    var newUser = new Users()
                    {
                        User = user,
                        Roles = _userManager.GetRolesAsync(user).GetAwaiter().GetResult() as List<string>
                    };
                    model.Users.Add(newUser);
                }
                return View(model);
            }
            return NotFound();
        }

        [HttpGet]
        [ActionName("Profile")]
        public async Task<IActionResult> GetUserProfile(string id)
        {
            ApplicationUser user;
            if(id == null)
            {
                user = ApplicationDbContext.Users
                    .Include(u => u.Fanfiks)
                    .Include(u => u.Comments)
                    .FirstOrDefault(u => u.Id == CurrentUser.Id);
            }
            else
            {
                user = ApplicationDbContext.Users
                    .Include(u => u.Fanfiks)
                    .Include(u => u.Comments)
                    .FirstOrDefault(u => u.Id == id);
            }

            var model = new UserViewModel()
            {
                User = user,
                IsAdmin = await _userManager.IsInRoleAsync(user, "Admin")
            };

            return View(model);
        }

        [Authorize]
        public JsonResult ChangeTheme(string id)
        {
            var user = ApplicationDbContext.Users.FirstOrDefault(u => u.Id == id);
            if(user != null)
            {
                if (user.Theme == "Dark")
                    user.Theme = "Light";
                else
                    user.Theme = "Dark";

                ApplicationDbContext.Users.Update(user);
                ApplicationDbContext.SaveChanges();
                return Json(1);
            }
            return Json(0);
        }

        [Authorize]
        public async Task<IActionResult> Admin()
        {
            if (!IsAdmin)
                return NotFound();

            var users = ApplicationDbContext.Users
                .Include(u => u.Fanfiks)
                .Include(u => u.Comments)
                .ToList();

            var model = new UsersViewModel() { Users = new List<Users>() };

            foreach (var user in users)
            {
                var newUser = new Users()
                {
                    User = user,
                    Roles = await _userManager.GetRolesAsync(user) as List<string>
                };
                model.Users.Add(newUser);
            }
            return View(model);
        }

        public IActionResult Statistics()
        {
            if (!IsAdmin)
                return NotFound();

            float todayFanfikCount = ApplicationDbContext.Fanfik
                .Where(f => f.Updated >= DateTime.Now.AddHours(-24))
                .Count();
                    
            float todayUserCount = ApplicationDbContext.Users
                .Where(u => u.Created >= DateTime.Now.AddHours(-24))
                .Count();

            float todayCommentCount = ApplicationDbContext.Comment
                .Where(c => c.Created >= DateTime.Now.AddHours(-24))
                .Count();

            float mounthFanfikCount = ApplicationDbContext.Fanfik
                .Where(f => f.Updated >= DateTime.Now.AddDays(-30))
                .Count();

            float mounthUserCount = ApplicationDbContext.Users
                .Where(u => u.Created >= DateTime.Now.AddDays(-30))
                .Count();

            float mounthCommentCount = ApplicationDbContext.Comment
                .Where(c => c.Created >= DateTime.Now.AddDays(-30))
                .Count();

            float totalFanfikCount = ApplicationDbContext.Fanfik.Count();
            float totalUserCount = ApplicationDbContext.Users.Count();
            float totalCommentCount = ApplicationDbContext.Comment.Count();

            var model = new StatViewModel()
            {
                TodayFanfiksCount = todayFanfikCount,
                TodayUserCount = todayUserCount,
                TodayCommentCount = todayCommentCount,

                MounthFanfiksCount = mounthFanfikCount,
                MounthCommentCount = mounthCommentCount,
                MounthUserCount = mounthUserCount,

                FanfiksCount = totalFanfikCount,
                UsersCount = totalUserCount,
                CommentsCount = totalCommentCount
            };
            return View(model);
        }
    }
}

FanfikSite/Views/User/Admin.cshtml
@model FanfikSite.Models.UserViewModels.UsersViewModel
@{
    ViewData["Title"] = Localizer["Home"];
}
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" type="text/css" href="~/css/users.css">

<br><br>
<div class="container">
    <div class="well span8">

        @foreach (var user in Model.Users)
        {
            <div class="row-fluid user-row user_@user.User.Id">
                <div class="span1">
                    @if (user.User.Avatar != null)
                    {
                        <img class="img-circle"
                             src="@user.User.Avatar"
                             alt="@Localizer["UserPic"]">
                    }
                    else
                    {
                        <img class="img-circle"
                             src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=50"
                             alt="@Localizer["UserPic"]">
                    }
                </div>

                <div class="span10">
                    <strong>@user.User.UserName</strong><br>
                    <span class="text-muted">
                        @if (user.Roles.Contains("Admin"))
                        {
                            <p>@Localizer["Admin"]</p>

                        }
                        else
                        {
                            <p>@Localizer["UserSlave"]</p> 
                        }
                        
                    </span>
                </div>
                <div class="span1 dropdown-user" data-for=".@user.User.UserName.Replace(".","").Replace("@","")">
                    <i class="icon-chevron-down text-muted"></i>
                </div>
            </div>
            <div class="row-fluid user-infos @user.User.UserName.Replace(".","").Replace("@","") info_@user.User.Id">
                <div class="span10 offset1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">@Localizer["Information"]</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row-fluid">
                                <div class="span3">
                                    @if (user.User.Avatar != null)
                                    {
                                        <img class="img-circle"
                                             src="@user.User.Avatar"
                                             alt="@Localizer["UserPic"]">
                                    }
                                    else
                                    {
                                        <img class="img-circle"
                                             src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=50"
                                             alt="@Localizer["UserPic"]">
                                    }
                                </div>
                                <div class="span6">
                                    <strong>@user.User.UserName</strong><br>
                                    <table class="table table-condensed table-responsive table-user-information">
                                        <tbody>
                                            <tr>
                                                <td>@Localizer["Level"]</td>
                                                @if (user.Roles.Contains("Admin"))
                                                {
                                                    <td>@Localizer["Administrator"]</td>

                                                }
                                                else
                                                {
                                                    <td>@Localizer["Slave"]</td>
                                                }
                                            </tr>
                                            <tr>
                                                <td>@Localizer["Registered"]</td>
                                                <td>11/12/2013</td>
                                            </tr>
                                            <tr>
                                                <td>@Localizer["Fanfiks"]</td>
                                                <td>@user.User.Fanfiks.Count</td>
                                            </tr>
                                            <tr>
                                                <td>@Localizer["Commnets"]</td>
                                                <td>@user.User.Comments.Count</td>
                                            </tr>
                                            <tr>
                                                @if ((user.User.LockoutEnd == null) || (user.User.LockoutEnd <= DateTime.Now))
                                                {
                                                    <td><button class="btn btn-primary block" data-id="@user.User.Id">Block</button></td>
                                                    <td><button class="btn btn-primary unblock" data-id="@user.User.Id" style="display:none">Unblock</button></td>

                                                }
                                                else
                                                {
                                                    <td><button class="btn btn-primary unblock" data-id="@user.User.Id">Unblock</button></td>
                                                    <td><button class="btn btn-primary block" data-id="@user.User.Id" style="display: none">Block</button></td>
                                                }
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer" style="height:50px">
                            @if (!user.Roles.Contains("Admin"))
                            {
                                <button class="btn btn-primary add-admin" data-id="@user.User.Id" type="button"
                                        data-toggle="tooltip"
                                        data-original-title="Add admin">
                                    <i class="fa fa-address-book "></i>
                                </button>
                            }
                            <span class="pull-right">
                                <button class="btn btn-danger delete" data-id="@user.User.Id" type="button"
                                        data-toggle="tooltip"
                                        data-original-title="Remove this user">
                                    <i class="icon-remove icon-white"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

        }
        
    </div>
</div>

<environment include="Development">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="~/js/admin.js"></script>
</environment>

FanfikSite/Views/User/Profile.cshtml
@model FanfikSite.Models.UserViewModels.UserViewModel
@{
    ViewData["Title"] = Localizer["Home"];
}

<environment include="Development">
    <link rel="stylesheet" type="text/css" href="~/css/profile.css" />
</environment>

<div>
    <div class="row">
        <div class="col-md-3 user">
            <div class="user_photo">
                @if (Model.User.Avatar != null)
                {
                    <img src="@Model.User.Avatar" />
                }
                else
                {
                    <img src="~/images/no_avatar.png" />
                }
                <h4>@Model.User.UserName</h4>
            </div>
            <div class="display_count_story_comment">
                <div class="row">
                    <h5>@Localizer["Fanfiks"] @Model.User.Fanfiks.Count</h5>
                </div>
                <div class="row">
                    <h5>@Localizer["Comments"] @Model.User.Comments.Count</h5>
                </div>
                <div class="row">
                    @if (UserOperation.GetCurrentUser(User).Theme == "Dark")
                    {
                        <a class="btn btn-default" name="changeTheme" id="changeTheme" onclick="chageTheme()">Light Theme</a>
                    }
                    else
                    {
                        <a class="btn btn-default" name="changeTheme" id="changeTheme" onclick="chageTheme()">Dark Theme</a>
                    }

                    <input type="hidden" name="userId" id="userId" value="@Model.User.Id">

                </div>
                <div class="row">
                    <a asp-controller="Manage" asp-action="Index"><h5>@Localizer["Settings"]</h5></a>
                </div>
                <div class="local">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
            </div>

        </div>
        <div class=" col-md-9 user_character">
            <table class="table">
                <tbody>
                    <tr>
                        <td><p>@Localizer["Email"]</p></td>
                        <td><p class="right">@Model.User.Email</p></td>
                    </tr>
                    <tr>
                        <td><p>@Localizer["Phone"]</p></td>
                        <td><p class="right">@Model.User.PhoneNumber</p></td>
                    </tr>
                    <tr>
                        <td><a asp-controller="Post" asp-action="CreatePost" asp-route-id="@Model.User.Id" class="btn btn-default"><h4 class="button">@Localizer["WriteStory"]</h4></a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="story col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"><p class="text-center">@Localizer["Image"]</p></th>
                    <th scope="col"><p class="text-center">@Localizer["Title"]</p></th>
                    <th scope="col"><p class="text-center">@Localizer["CreationDate"]</p></th>
                </tr>
            </thead>
            <tbody>
            @{
                var id = 0;
                @foreach (var fanfik in Model.User.Fanfiks)
                {
                    <tr class="list_story">
                        <td><img src="@fanfik.Image" style="width:100px; height:auto"/></td>
                        <td  id="@id">
                        <p class="text-center">
                            <a asp-action="Get" asp-controller="Post" asp-route-id="@fanfik.Id">@fanfik.Title</a>
                        </p></td>
                        <td><p class="text-center">@fanfik.Created</p></td>
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
</div>

<environment include="Development">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="~/js/profile.js"></script>
</environment>

FanfikSite/Views/User/_Layout.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    var userRoles = await UserManager.GetRolesAsync(UserOperation.GetCurrentUser(User));
}

<link rel="stylesheet" type="text/css" href="~/css/admin.css">
<link rel="stylesheet" type="text/css" href="~/css/site.css" />

<body class="home">
    <div class="container-fluid display-table">
        <div class="row display-table-row">
            @if (userRoles.Contains("Admin"))
            {
                <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
                    <div class="navi">
                        <ul>
                            <li><a asp-controller="User" asp-action="Profile"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">@Localizer["Home"]</span></a></li>
                            <li><a asp-controller="User" asp-action="Statistics"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">@Localizer["Statistic"]</span></a></li>
                            <li class="active"><a asp-controller="User" asp-action="Admin"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">@Localizer["Users"]</span></a></li>
                            <li><a asp-controller="Manage" asp-action="Index"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">@Localizer["Setting"]</span></a></li>
                        </ul>
                    </div>
                </div>
            }
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                
                <div class="user-dashboard">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

@section Scripts {
    @RenderSection("Scripts", required: false)
}